### ISSUE TITLE
Create distribution repository

### ISSUE THREAD

**Issue by hauleth** [redox-os/website#1]
I will need additional repository named `redox-os.github.io` for deployment.

**Comment by hauleth** [comment]
And setup domain for that page ([tutorial](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/)) and send me info which domain you chosen.

**Comment by hauleth** [comment]
cc @jackpot51

**Comment by jackpot51** [comment]
Thanks, I will do that soon.

**Comment by hauleth** [comment]
For now you can check result on https://redox-os.github.io

**Comment by jackpot51** [comment]
It looks good so far!
