### ISSUE TITLE
RSS feeds for blog and TWiRx 

### ISSUE THREAD

**Issue by NobbZ** [redox-os/website#12]
Please add them, they are missing!

**Comment by Ticki** [comment]
http://www.redox-os.org/news/index.xml

**Comment by NobbZ** [comment]
It's still not linked from the page. Dunno if it is a linked resource in
the htmls header though, neither my Desktop nor my mobile browser would
make any use of that information...

Ticki <notifications@github.com> schrieb am Sa., 24. Okt. 2015 20:16:

**Comment by hauleth** [comment]
Atom feed doesn't work in article view. You need to view list of articles or homepage to get feed link tag. For each category there exist `index.xml` file that is Atom feed.

**Comment by NobbZ** [comment]
There is no link to the feed as you can see:
![nofeeds](https://cloud.githubusercontent.com/assets/58951/10712348/e331c6de-7a98-11e5-9a15-77ac84aa72a7.png)
I know that some Browsers are capable to extract the link to atom or RSS feeds from //header/link or something like that, but my browser and perhaps the browsers of many more people are not!
For android there is not a single browser that is capable of extracting that metadata, and I am using my mobile as primary reading device for aggregated news. When I'm at my desktop I want to work and not  get distracted by a Feedreader, while I have plenty of time during lectures or when on bus to check Feeds, Reddit and Mails on mobile.
Thats why I am asking for a simple clickable link on the Blog/TWiRx overview.

**Comment by hauleth** [comment]
Ok. Will add one.

**Comment by Ticki** [comment]
Can be closed.
