### ISSUE TITLE
Devel Chat Down?

### ISSUE THREAD

**Issue by MggMuggins** [redox-os/website#182]
I guess this is in scope here since the chat is hosted under the `redox-os.org` domain... In any case, is the chat down or am I experiencing client-side issues or what? I shot an e-mail at info@redox-os.org but haven't gotten anything from there.

**Comment by jackpot51** [comment]
It is not down, please try this link: https://chat.redox-os.org/redox/channels/town-square

**Comment by MggMuggins** [comment]
Nope, all I get is a blank off-white screen, occasionally loading dots on page load and then nothing. I've tried with firefox, I'll try again.

**Comment by stratact** [comment]
@ticki how's the server update coming along? I'm not able to access the chat server for a while now.

**Comment by jackpot51** [comment]
I am unable to send messages

**Comment by stratact** [comment]
Just don't log out like I did because you won't be able to log back in with an error that says: "We couldn't update the failed_attempts"

**Comment by stratact** [comment]
Okay, now it says `We couldn't find an account matching your login credentials.`, so I think my account probably got deleted somehow

**Comment by jackpot51** [comment]
I am getting the same thing

**Comment by stratact** [comment]
@jackpot51 I didn't realize how Mattermost updates would be not that stable and since @ticki left open source and wouldn't be as around to fix things, we probably might want to cut our losses and move our base to a less independent solution, like gitter, if worst comes to worst. Or, ticki should give you the rights to the Mattermost server so you can maintain it when problems show up.

**Comment by jackpot51** [comment]
Mattermost is back up, there was an issue with disk space. It is up to @ticki if he wants to host it or not, I am open to moving it to my own server.

I am not on board with moving away from Mattermost. Everything else sucks, from my experience.
