### ISSUE TITLE
Wrong links in Dictator feed

### ISSUE THREAD

**Issue by antoyo** [redox-os/website#20]
Hello.
The links in the [dictator](http://dictator.redox-os.org/feed.php) feed are wrong.

For instance, the link http://redox-os.org/index.php?controller=post&amp;action=view&amp;id_post=17 should be http://dictator.redox-os.org/index.php?controller=post&amp;action=view&amp;id_post=17.

Thanks to fix this issue.

**Comment by jackpot51** [comment]
Thanks, will fix!

**Comment by jackpot51** [comment]
Fixed for new items
