### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by Ticki** [redox-os/website#26]

**Comment by Ticki** [comment]
ping @hauleth

**Comment by hauleth** [comment]
What should be in description?

**Comment by Ticki** [comment]
Something like "The redox website and blog"

**Comment by Ticki** [comment]
@hauleth :point_up:

**Comment by Ticki** [comment]
No, what I meant was a repository description..

**Comment by Ticki** [comment]
Nevermind, jackpot fixed it.
