### ISSUE TITLE
Fix ZFS to OpenZFS on the front page

### ISSUE THREAD

**Issue by shmerl** [redox-os/website#40]
Right now the site says: _ZFS Filesystem Support (WIP)_

It surely refers to OpenZFS which is a different filesystem than ZFS. OpenZFS is FOSS and it already diverged from closed source ZFS owned by Oracle. They are incompatible and there is no goal to keep them compatible in the future. So to avoid confusion, please call it with correct name - OpenZFS.

**Comment by jackpot51** [comment]
This is not true at all. Our implementation relies on the on-disk structures defined by ZFS, and is not related to OpenZFS.

**Comment by Ticki** [comment]
OpenZFS is just a open resource of information about ZFS. The file system is the same.

**Comment by Ticki** [comment]
Damn, you were faster than me, @jackpot51. ;P

**Comment by shmerl** [comment]
No, they aren't the same. See http://open-zfs.org/wiki/FAQ#Are_pools_created_by_Solaris_compatible_with_OpenZFS.3F

`Are pools created by Solaris compatible with OpenZFS?
Yes, if created with pool version 28 or earlier.
Oracle's closed source uses of pool versions 29–35 are not compatible`

Please do your research.

**Comment by Ticki** [comment]
> created

It is still the same FS.

**Comment by shmerl** [comment]
@Ticki no, it's not. Did you talk to developers of OpenZFS about it? They can explain it better.

**Comment by Ticki** [comment]
And the on-disk representation of redox-os/zfs is following the ZFS specs, not OpenZFS.

**Comment by Ticki** [comment]
In any case, it is not related to OpenZFS **at all**.

**Comment by shmerl** [comment]
OK, thanks for clarifying. Then why are you following specs of proprietary closed filesystem?

**Comment by jackpot51** [comment]
We are not, not, not, not *NOT* OpenZFS. You must understand this. We are not looking to reimplement OpenZFS, rather, to produce a ZFS implementation in Rust that is our own, and may be incompatible with others.

**Comment by Ticki** [comment]
> Then why are you following specs of proprietary closed filesystem instead of the open one?

The specification is not proprietary.

**Comment by jackpot51** [comment]
The on-disk spec we are using is BSD licensed: http://www.giis.co.in/Zfs_ondiskformat.pdf

**Comment by shmerl** [comment]
Are you sure? What about patents? OpenZFS is covered by patents released for it (as per CDDL). Do you have Oracle's permission for reimplementing closed ZFS?

**Comment by jackpot51** [comment]
We don't need Oracle's or OpenZFS's permission to do a black-box reimplementation

**Comment by shmerl** [comment]
Copyright wise no, patent wise - sure you need it.

**Comment by Ticki** [comment]
The Oracle **implementation** is proprietary, the specs are not.

**Comment by shmerl** [comment]
Remember, Oracle already attacked many on patent grounds. Including Google.

**Comment by jackpot51** [comment]
What patents would potentially be breached by our implementation?

**Comment by shmerl** [comment]
No idea, I'm not a patent expert on ZFS. But I'm also sure Oracle has quite a number of them there. If you need legal advice on that, I recommend you contacting some FOSS legal experts and consult with them on this. Otherwise you are literally walking into a minefield.

**Comment by Ticki** [comment]
ZFS is just a specification of an on-disk representation, they can only patent certain aspects of the implementation, which is based on the BSD licensed OpenSolaris one.

**Comment by jackpot51** [comment]
I do see a potential issue with trademark: https://tsdrapi.uspto.gov/ts/cd/casestatus/sn85901629/content (which can be solved by renaming the implementation)

**Comment by jackpot51** [comment]
Perhaps this is a relevant patent: http://www.google.com/patents/US6289356

**Comment by jackpot51** [comment]
NetApp filed these patents, among others: http://en.swpat.org/wiki/NetApp's_filesystem_patents

**Comment by shmerl** [comment]
To be safe - OpenZFS is already covered for FOSS usage by all relevant patents. So if you stick to implementing format of OpenZFS you'd be safer. If you claim you implement ZFS in contrast - that's risky. But again, don't take my word for it. Be diligent and contact legal experts. OpenZFS project itself should have some of them involved.
