### ISSUE TITLE
2 websites?

### ISSUE THREAD

**Issue by genodeftest** [redox-os/website#41]
There are 2 repositories for websites: https://github.com/redox-os/redox-os.github.io and https://github.com/redox-os/redox . redox-os.github.io is just getting a HTTP redirect to redox-os.org so is there any use keeping it?

**Comment by jackpot51** [comment]
redox-os.github.io is the real website repository, there is no website stuff in redox

**Comment by genodeftest** [comment]
It would be useful to state that in redox-os/redox-os.github.io repository's description.
