### ISSUE TITLE
[Discourse Forum] seems to be unable to send mails

### ISSUE THREAD

**Issue by genodeftest** [redox-os/website#42]
I signed up at the discourse forum https://discourse.redox-os.org/, but I haven't received a confirmation mail so far. Is it possible that those emails are not getting through to my email server? I've seen this problem before with @Ticki trying to invite me to mattermost.

This might be due to using a non-trusted (self-signed) TLS certificate or not using any certificate at all.

Note: I never had this kind of issue, signing up for https://users.rust-lang.org/ worked fine too.

**Comment by Ticki** [comment]
They run on different servers, so I believe it is a problem with your server. Also, they both use LetsEncrypt, do your server accept that?

**Comment by genodeftest** [comment]
I don't know since I don't operate it myself. But since LetsEncrypt is signed by a trusted CA, this should not be a problem.

**Comment by Ticki** [comment]
> LetsEncrypt is signed by a trusted CA

LetsEncrypt **is** a CA.

**Comment by genodeftest** [comment]
> LetsEncrypt **is** a CA.

Yes, but it is not trusted directly by any major software (CA store).

Anyway, that should not matter. I don't know what is wrong with the mail servers. And I don't know for sure which one to blame. Is your other mattermost server running on the rust-lang.org domain too? If yes, is it possible that the rust-lang.org domain just landed on some spam server blacklist? It is getting one match on http://www.blacklistalert.org/

**Comment by Ticki** [comment]
> Yes, but it is not trusted directly by any major software (CA store).

It actually is!

**Comment by genodeftest** [comment]
> > Yes, but it is not trusted directly by any major software (CA store).
> It actually is!

Whatever.

Since this is to a domain blacklisted and probably none of us can do anything about it I'm closing this report and will try again later.

**Comment by genodeftest** [comment]
Or can you try registering a new account?

**Comment by jackpot51** [comment]
I found the issue - the mail service was not running

Everyone will probably start getting mails soon

**Comment by genodeftest** [comment]
Confirmed, I just received a confirmation mail that should have been sent yesterday.
