### ISSUE TITLE
Add chat links

### ISSUE THREAD

**Issue by Mouvedia** [redox-os/website#43]
## General

- `#redox` (irc.mozilla.org)
- request Mattermost invite

## <del>Teams</del>
<del>redox-os/redox#41</del>

**Comment by Ticki** [comment]
Teams is dead. Could you submit a PR for chat link?

**Comment by Mouvedia** [comment]
@Ticki What's the Gitter room?

If I PR it won't be on this repository.

**Comment by Ticki** [comment]
There is no Gitter room.

**Comment by Mouvedia** [comment]
@Ticki you should close redox-os/redox#41

Is there a Slack team?

**Comment by Ticki** [comment]
> Is there a Slack team?

No, but there is a Mattermost chat.

**Comment by Ticki** [comment]
Shall I send an invite for you?

**Comment by Mouvedia** [comment]
@Ticki Yes, please.

**Comment by Ticki** [comment]
What ya' email?

**Comment by Mouvedia** [comment]
> This team has reached the maxmium number of allowed accounts. Contact your systems administrator to set a higher limit.

**Comment by Ticki** [comment]
Well, well, well. Will look into that.

**Comment by Ticki** [comment]
Fixed.

**Comment by rjgoldsborough** [comment]
I can add these links. Do we want to add a "Chat" link to the menu? Or a more general "Contact" or "Contribute" page?

If not a new page, where should they go?

It looks like there is a mattermost invite link too http://docs.mattermost.com/help/getting-started/managing-members.html#team-invite-link

**Comment by ca1ek** [comment]
Contact page would be good. Chat, not so much as it's not public, but
invite. You could make a page saying that to join the chat you need to send
an email to x address.
