### ISSUE TITLE
[Documentation] rustdoc on doc.redox-os.org has broken links to source files

### ISSUE THREAD

**Issue by genodeftest** [redox-os/website#45]
Steps to reproduce:
1. look at [any .rs file documentation](https://doc.redox-os.org/kernel/schemes/file/struct.FileScheme.html) on doc.redox-os.org
2. click on the `[src]` link on the right side

What happens:
the `[src]` link points to https://doc.redox-os.org/src/kernel/kernel/schemes/file.rs.html.html#218-220, which gives a HTTP 404 status code

What should happen:
It should point to https://doc.redox-os.org/src/kernel/kernel/schemes/file.rs.html#218-220

**Comment by jackpot51** [comment]
Thanks, will look into fixing it
