### ISSUE TITLE
Inconsistent redirection when using http vs https

### ISSUE THREAD

**Issue by seppestas** [redox-os/website#66]
When requesting [redox-os.org](redox-os.org) or http://redox-os.org you get redirected to http://www.redox-os.org/. However, when requesting https://redox-os.org you get a 404 Not Found. I would expect this request to redirect to https://www.redox-os.org.

I would also prefer to have the redirection work the other way around: have www.redox-os.org forwarded to redox-os.org, and if no protocol is specified, have it default to https instead of http.
It's 2016. https is not the exception, it's the rule (and free, thanks to [letsencrypt.org](letsencrypt.org)).

Somewhat related to #58.

**Comment by jackpot51** [comment]
This will be fixed now. I will not force redirection to https until OpenSSL on Ubuntu supports chacha20-poly1305
